# Generated by Django 5.2 on 2025-04-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.TextField()),
                ('title', models.TextField()),
                ('published_date', models.DateTimeField()),
                ('last_modified_date', models.DateTimeField(auto_now_add=True)),
                ('mkdwn_content', models.TextField()),
            ],
        ),
    ]
